name: flutter_app_technothlon
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chewie:
  video_player:
  google_fonts:
  loading_animations:
  page_view_indicators:
  double_back_to_close_app:
  firebase_core:
  firebase_database:
  cloud_firestore:
  firebase_analytics:
  google_sign_in:
#  firebase_auth:
  flutter_facebook_login:
  page_transition:
  percent_indicator:
  youtube_player_flutter:
  flutter_youtube_view:
  firebase_messaging:
  connectivity:
#  flutter_svg: 0.18.0
  flutter_svg: 0.21.0-nullsafety.0
  flutter_webview_plugin:
  font_awesome_flutter:
  cupertino_icons:
  extended_image:
  url_launcher:
  url_launcher_web:
  webview_flutter:
  flip_card:
#  flutter_downloader:
  dio:
  permission_handler:
  downloads_path_provider:
  flutter_swiper:
  table_calendar: ^3.0.1
  flutter_inappwebview:
  firebase_image:
    git:
      url: git://github.com/blinkin/firebase_image.git
      ref: issue37_fix
  url_launcher_platform_interface:
  plugin_platform_interface:
  flutter_share:
  share:
  firebase_auth:
  rxdart:
  shared_preferences:
  scroll_snap_list:
  flutter_launcher_icons:
  flutter_offline:
  image_picker: ^0.8.1+1
  provider:
  mailer:
  path_provider:
  flutter_email_sender: ^5.0.1

#dependency_overrides:
#  url_launcher: 5.7.10
dev_dependencies:
  flutter_test:
    sdk: flutter
#  url_launcher: ^5.5.0

flutter_icons:
  image_path: "link_logo/logo.png"
  android: true
  ios: false


  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  plugin:
    platforms:
      android:
        package: com.hoanglm.flutteryoutubeview
        pluginClass: FlutterYoutubeViewPlugin
      ios:
        pluginClass: FlutterYoutubeViewPlugin
  uses-material-design: true
  assets:
    - images/
#    - images/experiment/
    - assets/logo.png
    - assets/images/
    - assets/icons/
    - assets/new_icons/
#    - heads_images/
#    - dev_images/
    - link_logo/
#    - assets/videos/Logic is All You Need - Official Curtain Raiser 2020.mp4
    - assets/

        

  fonts:
    - family: Circular
      fonts:
        - asset: fonts/CircularStd-Medium.ttf
        - asset: fonts/CircularAir-Light.ttf
          weight: 100
        - asset: fonts/CircularStd-Bold.ttf
          weight: 500
    - family: sniglet
      fonts:    
        - asset: fonts/Sniglet-Regular.ttf
    - family: Varela
      fonts:
        - asset: fonts/VarelaRound-Regular.ttf
          weight: 100

        
        
        
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
